import type { NextPage } from "next";
import Script from "next/script";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState, useRef } from "react";

const Home: NextPage = () => {
  const [breakLength, setBreakLength] = useState(5);
  const [sessionLength, setSessionLength] = useState(25);
  const [timer, setTimer] = useState(25 * 60);
  const [timerString, setTimerString] = useState("25:00");
  const [isRunning, setIsRunning] = useState(false);
  const [isBreak, setIsBreak] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    //update timer string
    const minutes = Math.floor(timer / 60);
    const seconds = timer % 60;
    setTimerString(
      `${minutes < 10 ? "0" + minutes : minutes}:${
        seconds < 10 ? "0" + seconds : seconds
      }`
    );

    if (timer === 0) {
      if (isBreak) {
        setTimeout(() => {
          setTimer(sessionLength * 60);
          setIsBreak(false);
        }, 1000);
        audioRef.current?.play();
      } else {
        setTimeout(() => {
          setTimer(breakLength * 60);
          setIsBreak(true);
        }, 1000);
        audioRef.current?.play();
      }
    }
  }, [timer, isRunning]);

  useEffect(() => {
    if (isRunning) {
      const interval = setInterval(() => {
        setTimer(timer - 1);
      }, 1000);
      return () => clearInterval(interval);
    }
  }, [isRunning, timer]);

  useEffect(() => {
    setTimer(sessionLength * 60);
  }, [sessionLength]);

  const handleStartStop = () => {
    if (isRunning) {
      console.log("stop");
    } else {
      console.log("start");
    }
    setIsRunning(!isRunning);
  };

  const handleReset = () => {
    setIsBreak(false);
    setBreakLength(5);
    setSessionLength(25);
    setIsRunning(false);
    setTimer(25 * 60);

    if (audioRef.current) {
      audioRef.current.load();
    }
  };

  const handleBeakDecrement = () => {
    if (isRunning) return;
    if (breakLength > 1) {
      setBreakLength(breakLength - 1);
    }
  };
  const handleBeakIncrement = () => {
    if (isRunning) return;
    if (breakLength < 60) {
      setBreakLength(breakLength + 1);
    }
  };
  const handleSessionDecrement = () => {
    if (isRunning) return;
    if (sessionLength > 1) {
      setSessionLength(sessionLength - 1);
    }
  };
  const handleSessionIncrement = () => {
    if (isRunning) return;
    if (sessionLength < 60) {
      setSessionLength(sessionLength + 1);
    }
  };

  return (
    <div className="">
      <Script
        src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"
        strategy="beforeInteractive"
      ></Script>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto flex w-screen flex-col gap-2 bg-orange-700 md:max-w-xl">
        <div className="text-center text-3xl">Pomodoro Technique</div>
        <div className="flex flex-row justify-center text-2xl">
          <div className="basis-32">
            <div className="text-center" id="break-label">
              Break
            </div>
            <div className="flex flex-row justify-center">
              <button id="break-decrement" onClick={handleBeakDecrement}>
                -
              </button>
              <div id="break-length">{breakLength}</div>
              <button id="break-increment" onClick={handleBeakIncrement}>
                +
              </button>
            </div>
          </div>
          <div className="basis-32">
            <div className="text-center" id="session-label">
              Session
            </div>
            <div className="flex flex-row justify-center">
              <button id="session-decrement" onClick={handleSessionDecrement}>
                -
              </button>
              <div id="session-length">{sessionLength}</div>
              <button id="session-increment" onClick={handleSessionIncrement}>
                +
              </button>
            </div>
          </div>
        </div>
        <div className="mx-auto flex w-36 flex-col rounded border-2 border-orange-800 py-2">
          <div className="text-center" id="timer-label">
            {isBreak ? "Break" : "Session"}
          </div>
          <div className="text-center text-5xl" id="time-left">
            {timerString}
          </div>
          <audio src="/time-up-ringtone.mp3" id="beep" ref={audioRef}></audio>
        </div>
        <div className="flex flex-row justify-center">
          <button
            className="basis-16"
            id="start_stop"
            onClick={handleStartStop}
          >
            Start/Pause
          </button>
          <button className="basis-16" id="reset" onClick={handleReset}>
            Reset
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;
