import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

const Home: NextPage = () => {
  const [breakLength, setBreakLength] = useState(5);
  const [sessionLength, setSessionLength] = useState(25);
  const [timer, setTimer] = useState(25 * 60);
  const handleReset = () => {
    setBreakLength(5);
    setSessionLength(25);
    setTimer(25 * 60);
  };
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto flex w-screen flex-col gap-2 bg-orange-700 md:max-w-xl">
        <div className="text-center text-3xl">Pomodoro Technique</div>
        <div className="flex flex-row justify-center text-2xl">
          <div className="basis-32">
            <div className="text-center" id="break-label">
              Break
            </div>
            <div className="flex flex-row justify-center">
              <div
                className="cursor-pointer"
                id="break-decrement"
                onClick={() => {
                  setBreakLength(breakLength - 1);
                }}
              >
                -
              </div>
              <div id="break-length">{breakLength}</div>
              <div
                className="cursor-pointer"
                id="break-increment"
                onClick={() => {
                  setBreakLength(breakLength + 1);
                }}
              >
                +
              </div>
            </div>
          </div>
          <div className="basis-32">
            <div className="text-center" id="session-label">
              Session
            </div>
            <div className="flex flex-row justify-center">
              <div
                className="cursor-pointer"
                id="session-decreament"
                onClick={() => {
                  setSessionLength(sessionLength - 1);
                }}
              >
                -
              </div>
              <div id="session-length">{sessionLength}</div>
              <div
                className="cursor-pointer"
                id="session-increament"
                onClick={() => {
                  setSessionLength(sessionLength + 1);
                }}
              >
                +
              </div>
            </div>
          </div>
        </div>
        <div className="mx-auto flex w-36 flex-col rounded border-2 border-orange-800 py-2">
          <div className="text-center" id="timer-label">
            Time
          </div>
          <div className="text-center text-5xl" id="time-left">
            {" "}
            25:00
          </div>
        </div>
        <div className="flex flex-row justify-center">
          <div className="basis-16" id="start_stop">
            Start
          </div>
          <div className="basis-16" id="">
            Pause
          </div>
          <div className="basis-16" id="reset">
            Reset
          </div>
        </div>
      </div>
      <script
        src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"
        defer
      ></script>
    </div>
  );
};

export default Home;
